# Generated by Django 6.1 on 2026-09-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_rebrand_lazarev'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='campaign_announcement_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_popups/'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='registration_bonus_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_popups/'),
        ),
    ]
