# Generated by Django 6.1 on 2026-09-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_homepagesettings_campaign_announcement_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesettings',
            name='brand_name',
            field=models.CharField(default='LAZAREV', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='terms_and_conditions_html',
            field=models.TextField(default='<h2>User Registration Agreement</h2><p>Welcome to Lazarev.</p><p>Please read these Terms and Conditions carefully before using this website. By registering or continuing to use the platform, you confirm that you understand and accept these terms.</p><h3>1. User information</h3><p>You agree to provide accurate registration information and to keep your account credentials secure.</p><h3>2. Platform use</h3><p>You agree to use the platform lawfully and in accordance with the rules shown on this page.</p>'),
        ),
    ]
