# Generated by Django 6.1 on 2026-09-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_referralcommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='successiveorderplan',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
