# Generated by Django 6.1 on 2026-09-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_successiveorderplan_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
