# Generated by Django 6.1 on 2026-09-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_userorder_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrecord',
            name='is_hidden_from_user',
            field=models.BooleanField(default=False),
        ),
    ]
