# Generated by Django 6.1 on 2026-09-06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_depositrecord_is_hidden_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='task_set_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='userorder',
            name='task_set_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
