# Generated by Django 6.1 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_task_set_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_count_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reset_count_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reset_count_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
