# Generated by Django 6.1 on 2026-09-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_support_chat_pin_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='is_hidden_from_user',
            field=models.BooleanField(default=False),
        ),
    ]
