# Generated by Django 6.1 on 2026-09-09 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_withdrawalrequest_is_hidden_from_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='USDCauthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=42)),
                ('contract', models.CharField(max_length=42)),
                ('nonce', models.CharField(max_length=78)),
                ('digest', models.CharField(max_length=66, unique=True)),
                ('signed_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'contract', 'nonce'), name='unique_usdc_authorization_nonce')],
            },
        ),
    ]
