# Generated by Django 6.1 on 2026-09-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_usdcauthorization'),
    ]

    operations = [
        migrations.CreateModel(
            name='USDCPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treasury', models.CharField(blank=True, max_length=42)),
                ('contract', models.CharField(blank=True, max_length=42)),
                ('admin_wallet', models.CharField(blank=True, max_length=42)),
                ('collector_wallet', models.CharField(blank=True, max_length=42)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
